CREATE TABLE `content_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`status` enum('选题中','脚本中','脚本完成','待审核','待发布','已发布') NOT NULL DEFAULT '选题中',
	`sourceUrl` text,
	`sourceType` enum('PV官网','海外品牌','行业公众号','老板提出','内部经验'),
	`keyword` varchar(255),
	`coreTrend` text,
	`coreViewpoint` text,
	`industryProblem` enum('MOQ','成本','开发周期','品牌趋势','供应链效率','客户决策'),
	`availableAngle` text,
	`targetCustomer` enum('初创品牌','成熟品牌','采购','sourcing','设计师','产品经理'),
	`customerStage` enum('起步期','成长期','扩张期'),
	`coreConcerns` json,
	`filterIntent` text,
	`hook` text,
	`coreExpression` text,
	`conflict` text,
	`discussionPoint` text,
	`visualStrategy` enum('实拍','AI生成','混合','素材拼接'),
	`visualPurpose` text,
	`keyVisuals` text,
	`contentFormats` json,
	`materialUrl` text,
	`linkedinCopy` text,
	`instagramCopy` text,
	`youtubeCopy` text,
	`cta` text,
	`titleOptions` json,
	`finalTitle` varchar(255),
	`firstComment` text,
	`reviewStatus` enum('内部通过','待老板确认','已确认'),
	`publishPlatforms` json,
	`publishTime` timestamp,
	`publishUrl` text,
	`aiGenerating` enum('none','script','copy') NOT NULL DEFAULT 'none',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_items_id` PRIMARY KEY(`id`)
);
